# -*- coding: utf-8 -*-
"""Cognitive_Load_Binary_Baseline.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eSJBOqqS6EHSFtQAwlTu21csMpY2kmUg

1. Import dataset from drive, so you gotta upload the file there
"""

# from google.colab import drive
# drive.mount("/content/drive")

import numpy as np
import pandas as pd
import matplotlib
matplotlib.use('Agg')  # Non-interactive backend
import matplotlib.pyplot as plt

SEED = 42
np.random.seed(SEED)

"""2. Load Dataset"""

CSV_PATH = "synthetic_mental_health_data.csv"
df = pd.read_csv(CSV_PATH)

print("Shape:", df.shape)
print("Columns:", df.columns.tolist())
df.head()

"""3. Binary labels

Threat (1) → anxious, stressed, overloaded, distracted

Safe (0) → calm, focused
"""

# Threat (1) → anxious, stressed, overloaded, distracted
# Safe (0) → calm, focused

df2 = df.copy()

# Normalize text just in case (strip spaces)
df2["Cognitive_State"] = df2["Cognitive_State"].astype(str).str.strip()

label_map = {
    # Threat
    "anxious": 1, "stressed": 1, "overloaded": 1, "distracted": 1,
    "Anxious": 1, "Stressed": 1, "Overloaded": 1, "Distracted": 1,

    # Safe
    "calm": 0, "focused": 0,
    "Calm": 0, "Focused": 0,

    # Your dataset variants (very important)
    "Cognitive Overload": 1
}

df2["y_bin"] = df2["Cognitive_State"].map(label_map)

# Drop any rows that didn't map cleanly
df2 = df2.dropna(subset=["y_bin"]).reset_index(drop=True)
df2["y_bin"] = df2["y_bin"].astype(int)

print("Binary label counts (0=Safe, 1=Threat):")
print(df2["y_bin"].value_counts())
print("\nUnique Cognitive_State values after cleanup:")
print(sorted(df2["Cognitive_State"].unique()))

"""4. Preprocessing: Categorical data --> Binary matrix"""

# Drop timestamp if present
if "Timestamp" in df2.columns:
    df2 = df2.drop(columns=["Timestamp"])

# Feature columns (adjust if needed)
base_cols = [c for c in ["GSR_Values", "Age", "Duration (minutes)"] if c in df2.columns]
eeg_cols  = [c for c in df2.columns if c.startswith("EEG_")]
prep_cols = [c for c in df2.columns if c.startswith("Preprocessed_")]
demo_cols = [c for c in ["Gender"] if c in df2.columns]  # keep for fairness later

feature_cols = base_cols + eeg_cols + prep_cols + demo_cols
print("Using features:", feature_cols)

X = df2[feature_cols].copy()

# One-hot encode categorical columns (Gender, etc.)
cat_cols = [c for c in X.columns if X[c].dtype == "object"]
if len(cat_cols) > 0:
    X = pd.get_dummies(X, columns=cat_cols, drop_first=False)

y = df2["y_bin"].values

print("X shape:", X.shape, "y shape:", y.shape)

"""5. Train-Test split + Scaling"""

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.20, random_state=SEED, stratify=y
)

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled  = scaler.transform(X_test)

print("Train:", X_train.shape, "Test:", X_test.shape)
print("Train counts:", pd.Series(y_train).value_counts().to_dict())
print("Test counts:", pd.Series(y_test).value_counts().to_dict())

"""6. Class weights for imbalance"""

from sklearn.utils.class_weight import compute_class_weight

classes = np.unique(y_train)
weights = compute_class_weight(class_weight="balanced", classes=classes, y=y_train)
class_weight_dict = {int(c): float(w) for c, w in zip(classes, weights)}

print("Class weights:", class_weight_dict)

"""7. Evaluation function"""

from sklearn.metrics import (
    accuracy_score, balanced_accuracy_score,
    precision_score, recall_score, f1_score,
    roc_auc_score, confusion_matrix, classification_report
)

def eval_binary(name, model, X_te, y_te):
    y_pred = model.predict(X_te)

    print(f"\n=== {name} ===")
    print("Accuracy:", round(accuracy_score(y_te, y_pred), 4))
    print("Balanced Acc:", round(balanced_accuracy_score(y_te, y_pred), 4))
    print("Precision (Threat=1):", round(precision_score(y_te, y_pred, zero_division=0), 4))
    print("Recall (Threat=1):", round(recall_score(y_te, y_pred, zero_division=0), 4))
    print("F1 (Threat=1):", round(f1_score(y_te, y_pred, zero_division=0), 4))

    if hasattr(model, "predict_proba"):
        y_prob = model.predict_proba(X_te)[:, 1]
        print("ROC-AUC:", round(roc_auc_score(y_te, y_prob), 4))

    print("\nReport:\n", classification_report(
        y_te, y_pred,
        target_names=["Safe(0)", "Threat(1)"],
        zero_division=0
    ))

    cm = confusion_matrix(y_te, y_pred)
    plt.figure(figsize=(5,4))
    plt.imshow(cm)
    plt.title(f"Confusion Matrix: {name}")
    plt.xlabel("Predicted")
    plt.ylabel("True")
    plt.colorbar()
    plt.show()

    return y_pred

"""8. Logistic Regression"""

from sklearn.linear_model import LogisticRegression

lr = LogisticRegression(max_iter=4000, random_state=SEED, class_weight="balanced")
lr.fit(X_train_scaled, y_train)

y_pred_lr = eval_binary("Logistic Regression (balanced)", lr, X_test_scaled, y_test)

"""9. Random Forest"""

from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(
    n_estimators=300,
    random_state=SEED,
    class_weight="balanced_subsample"
)
rf.fit(X_train, y_train)

y_pred_rf = eval_binary("Random Forest (balanced)", rf, X_test, y_test)

"""10. SVM"""

from sklearn.svm import SVC

svm = SVC(
    kernel="rbf",
    C=1.0,
    gamma="scale",
    probability=True,
    random_state=SEED,
    class_weight="balanced"
)
svm.fit(X_train_scaled, y_train)

y_pred_svm = eval_binary("SVM (RBF, balanced)", svm, X_test_scaled, y_test)

"""11."""

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

print("TensorFlow:", tf.__version__)

"""12. MLP"""

tf.random.set_seed(SEED)

input_dim = X_train_scaled.shape[1]

mlp_model = keras.Sequential([
    layers.Input(shape=(input_dim,)),
    layers.Dense(128, activation="relu"),
    layers.Dropout(0.3),
    layers.Dense(64, activation="relu"),
    layers.Dropout(0.3),
    layers.Dense(1, activation="sigmoid")
])

mlp_model.compile(
    optimizer=keras.optimizers.Adam(learning_rate=1e-3),
    loss="binary_crossentropy",
    metrics=["accuracy"]
)

callbacks = [keras.callbacks.EarlyStopping(monitor="val_loss", patience=5, restore_best_weights=True)]

mlp_model.fit(
    X_train_scaled, y_train,
    validation_split=0.15,
    epochs=50,
    batch_size=128,
    callbacks=callbacks,
    class_weight=class_weight_dict,
    verbose=1
)

y_prob_mlp = mlp_model.predict(X_test_scaled).ravel()
y_pred_mlp = (y_prob_mlp >= 0.5).astype(int)

# Quick eval
print("\n=== MLP (Keras, balanced) ===")
print("Accuracy:", round(accuracy_score(y_test, y_pred_mlp), 4))
print("Balanced Acc:", round(balanced_accuracy_score(y_test, y_pred_mlp), 4))
print("Precision (Threat=1):", round(precision_score(y_test, y_pred_mlp, zero_division=0), 4))
print("Recall (Threat=1):", round(recall_score(y_test, y_pred_mlp, zero_division=0), 4))
print("F1 (Threat=1):", round(f1_score(y_test, y_pred_mlp, zero_division=0), 4))
print("ROC-AUC:", round(roc_auc_score(y_test, y_prob_mlp), 4))
print(classification_report(y_test, y_pred_mlp, target_names=["Safe(0)", "Threat(1)"], zero_division=0))

"""13. 1D CNN"""

tf.random.set_seed(SEED)

X_train_cnn = X_train_scaled.reshape(X_train_scaled.shape[0], X_train_scaled.shape[1], 1)
X_test_cnn  = X_test_scaled.reshape(X_test_scaled.shape[0],  X_test_scaled.shape[1], 1)

cnn_model = keras.Sequential([
    layers.Input(shape=(X_train_cnn.shape[1], 1)),
    layers.Conv1D(64, 3, activation="relu"),
    layers.Conv1D(32, 3, activation="relu"),
    layers.MaxPooling1D(2),
    layers.Flatten(),
    layers.Dense(64, activation="relu"),
    layers.Dropout(0.3),
    layers.Dense(1, activation="sigmoid")
])

cnn_model.compile(
    optimizer=keras.optimizers.Adam(learning_rate=1e-3),
    loss="binary_crossentropy",
    metrics=["accuracy"]
)

callbacks = [keras.callbacks.EarlyStopping(monitor="val_loss", patience=5, restore_best_weights=True)]

cnn_model.fit(
    X_train_cnn, y_train,
    validation_split=0.15,
    epochs=50,
    batch_size=128,
    callbacks=callbacks,
    class_weight=class_weight_dict,
    verbose=1
)

y_prob_cnn = cnn_model.predict(X_test_cnn).ravel()
y_pred_cnn = (y_prob_cnn >= 0.5).astype(int)

print("\n=== 1D CNN (Keras, balanced) ===")
print("Accuracy:", round(accuracy_score(y_test, y_pred_cnn), 4))
print("Balanced Acc:", round(balanced_accuracy_score(y_test, y_pred_cnn), 4))
print("Precision (Threat=1):", round(precision_score(y_test, y_pred_cnn, zero_division=0), 4))
print("Recall (Threat=1):", round(recall_score(y_test, y_pred_cnn, zero_division=0), 4))
print("F1 (Threat=1):", round(f1_score(y_test, y_pred_cnn, zero_division=0), 4))
print("ROC-AUC:", round(roc_auc_score(y_test, y_prob_cnn), 4))
print(classification_report(y_test, y_pred_cnn, target_names=["Safe(0)", "Threat(1)"], zero_division=0))

"""14. Results"""

from sklearn.metrics import roc_auc_score

rows = []

def add_row(name, y_pred, y_prob=None):
    rows.append({
        "Model": name,
        "Accuracy": accuracy_score(y_test, y_pred),
        "Balanced_Acc": balanced_accuracy_score(y_test, y_pred),
        "Precision(Threat)": precision_score(y_test, y_pred, zero_division=0),
        "Recall(Threat)": recall_score(y_test, y_pred, zero_division=0),
        "F1(Threat)": f1_score(y_test, y_pred, zero_division=0),
        "ROC_AUC": roc_auc_score(y_test, y_prob) if y_prob is not None else np.nan
    })

add_row("LogReg", y_pred_lr, lr.predict_proba(X_test_scaled)[:, 1])
add_row("RandomForest", y_pred_rf, rf.predict_proba(X_test)[:, 1])
add_row("SVM", y_pred_svm, svm.predict_proba(X_test_scaled)[:, 1])
add_row("MLP", y_pred_mlp, y_prob_mlp)
add_row("1D CNN", y_pred_cnn, y_prob_cnn)

results_df = (
    pd.DataFrame(rows)
    .sort_values(by="F1(Threat)", ascending=False)
    .reset_index(drop=True)
)

results_df.style.set_caption(
    "Baseline Results: Threat = Cognitive Overload + Distracted, Safe = Focused"
)

print("\n" + "="*80)
print("FINAL RESULTS")
print("="*80)
print(results_df.to_string(index=True))
print("="*80)

"""15. SHAP Analysis on Random Forest - EEG Band Importance"""

print("\n" + "="*80)
print("SHAP ANALYSIS - Random Forest Feature Importance")
print("="*80)

import shap

# Create SHAP explainer for Random Forest
print("\nCreating SHAP explainer for Random Forest...")
explainer = shap.TreeExplainer(rf)

# Calculate SHAP values for test set
print("Calculating SHAP values for test set...")
shap_values = explainer.shap_values(X_test)

# For binary classification, shap_values might be a list [class_0, class_1]
# We want SHAP values for the positive class (Threat = 1)
if isinstance(shap_values, list):
    shap_values_threat = shap_values[1]  # Class 1 (Threat)
else:
    shap_values_threat = shap_values

print(f"SHAP values shape: {shap_values_threat.shape}")
print(f"SHAP values type: {type(shap_values_threat)}")

# Handle multi-dimensional SHAP values (for multi-output models)
if len(shap_values_threat.shape) == 3:
    # Shape is (n_samples, n_features, n_outputs)
    # Take the first output (or average across outputs)
    print(f"Multi-output detected, using first output dimension")
    shap_values_threat = shap_values_threat[:, :, 0]
    print(f"New SHAP values shape: {shap_values_threat.shape}")

# Get feature names
feature_names = X_test.columns.tolist()
print(f"\nFeature names ({len(feature_names)}): {feature_names}")

# Calculate mean absolute SHAP values for each feature
mean_abs_shap = np.abs(shap_values_threat).mean(axis=0)
print(f"Mean abs SHAP shape: {mean_abs_shap.shape}")

# Create feature importance dataframe
feature_importance_df = pd.DataFrame({
    'Feature': feature_names,
    'Mean_Abs_SHAP': mean_abs_shap
}).sort_values(by='Mean_Abs_SHAP', ascending=False)

print("\n" + "="*80)
print("FEATURE IMPORTANCE (Mean Absolute SHAP Values)")
print("="*80)
print(feature_importance_df.to_string(index=False))
print("="*80)

# Focus on EEG bands
# EEG_0 = Delta, EEG_1 = Theta, EEG_2 = Alpha, EEG_3 = Beta
eeg_features = ['EEG_0', 'EEG_1', 'EEG_2', 'EEG_3']
eeg_names = ['Delta (<4 Hz)', 'Theta (4-8 Hz)', 'Alpha (8-12 Hz)', 'Beta (13-30 Hz)']

eeg_importance = []
for eeg_feat in eeg_features:
    if eeg_feat in feature_names:
        idx = feature_names.index(eeg_feat)
        eeg_importance.append(mean_abs_shap[idx])
    else:
        eeg_importance.append(0.0)

eeg_importance_df = pd.DataFrame({
    'EEG_Band': eeg_names,
    'Feature_Name': eeg_features,
    'Mean_Abs_SHAP': eeg_importance
}).sort_values(by='Mean_Abs_SHAP', ascending=False)

print("\n" + "="*80)
print("EEG FREQUENCY BAND IMPORTANCE")
print("="*80)
print(eeg_importance_df.to_string(index=False))
print("="*80)

# Determine which EEG band contributes most
most_important_eeg = eeg_importance_df.iloc[0]
print(f"\n🎯 MOST IMPORTANT EEG BAND: {most_important_eeg['EEG_Band']}")
print(f"   Feature: {most_important_eeg['Feature_Name']}")
print(f"   Mean Absolute SHAP: {most_important_eeg['Mean_Abs_SHAP']:.6f}")

# Calculate percentage contribution among EEG bands
total_eeg_shap = eeg_importance_df['Mean_Abs_SHAP'].sum()
eeg_importance_df['Percentage'] = (eeg_importance_df['Mean_Abs_SHAP'] / total_eeg_shap * 100)

print("\n" + "="*80)
print("EEG BAND CONTRIBUTION (Percentage among EEG bands)")
print("="*80)
for idx, row in eeg_importance_df.iterrows():
    print(f"{row['EEG_Band']:20s} : {row['Percentage']:6.2f}%")
print("="*80)

# Save SHAP summary plot
print("\nGenerating SHAP summary plot...")
plt.figure(figsize=(10, 6))
shap.summary_plot(shap_values_threat, X_test, feature_names=feature_names, show=False)
plt.tight_layout()
plt.savefig('shap_summary_plot.png', dpi=150, bbox_inches='tight')
print("✓ Saved: shap_summary_plot.png")
plt.close()

# Save SHAP bar plot (feature importance)
print("Generating SHAP bar plot...")
plt.figure(figsize=(10, 6))
shap.summary_plot(shap_values_threat, X_test, feature_names=feature_names, plot_type="bar", show=False)
plt.tight_layout()
plt.savefig('shap_bar_plot.png', dpi=150, bbox_inches='tight')
print("✓ Saved: shap_bar_plot.png")
plt.close()

# Create custom EEG band comparison plot
print("Generating EEG band comparison plot...")
plt.figure(figsize=(10, 6))
colors = ['#1f77b4', '#ff7f0e', '#2ca02c', '#d62728']
bars = plt.bar(range(len(eeg_names)), eeg_importance_df['Mean_Abs_SHAP'], color=colors)
plt.xticks(range(len(eeg_names)), eeg_importance_df['EEG_Band'], rotation=45, ha='right')
plt.ylabel('Mean Absolute SHAP Value', fontsize=12)
plt.xlabel('EEG Frequency Band', fontsize=12)
plt.title('EEG Frequency Band Importance for Threat Detection\n(Random Forest Model)', fontsize=14, fontweight='bold')
plt.grid(axis='y', alpha=0.3)

# Add value labels on bars
for i, (bar, val) in enumerate(zip(bars, eeg_importance_df['Mean_Abs_SHAP'])):
    plt.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.001,
             f'{val:.4f}', ha='center', va='bottom', fontsize=10, fontweight='bold')

plt.tight_layout()
plt.savefig('eeg_band_importance.png', dpi=150, bbox_inches='tight')
print("✓ Saved: eeg_band_importance.png")
plt.close()

print("\n" + "="*80)
print("SHAP ANALYSIS COMPLETE!")
print("="*80)
print("\nGenerated files:")
print("  1. shap_summary_plot.png - Overall feature importance with value distribution")
print("  2. shap_bar_plot.png - Feature importance ranking")
print("  3. eeg_band_importance.png - EEG band comparison chart")
print("="*80)